apiVersion: v1
kind: ConfigMap
metadata:
  name: robosats-configmap
data:
  ALTERNATIVE_NAME: 'RoboSats Mainnet'
  ALTERNATIVE_SITE: 'RoboSats6tkf3eva7x2voqso3a5wcorsnw34jveyxfqi2fu7oyheasid.onion'
  AUTO_UNLOCK_PWD: '1234'
  BLOCK_TIME: "8"
  DEFAULT_BOND_SIZE: "3"
  DEFAULT_PUBLIC_ORDER_DURATION: "24"
  DISABLE_ONCHAIN: "False"
  ESCROW_USERNAME: 'admin'
  EXP_MAKER_BOND_INVOICE: '300 '
  EXP_TAKER_BOND_INVOICE: "200"
  FEE: "0.002"
  FIAT_EXCHANGE_DURATION: "24"
  HOST_NAME: ''
  HOST_NAME2: ''
  I2P_ALIAS: ''
  I2P_LONG: ''
  INVOICE_AND_ESCROW_DURATION: "30"
  LND_DIR: '/lnd/'
  LND_GRPC_HOST: 'lnd:10009'
  LOCAL_ALIAS: '127.0.0.1'
  MACAROON_PATH: 'data/chain/bitcoin/testnet/admin.macaroon'
  MAKER_FEE_SPLIT: "0.125"
  MARKET_PRICE_APIS: 'https://blockchain.info/ticker, https://api.yadio.io/exrates/BTC'
  MAX_BOND_SIZE: "15"
  MAX_MINING_NETWORK_SPEEDUP_EXPECTED: "1.7"
  MAX_PUBLIC_ORDER_DURATION: "24"
  MAX_PUBLIC_ORDERS: "100"
  MAX_SWAP_FEE: "0.1"
  MAX_SWAP_POINT: "0"
  MAX_TRADE: "3000000"
  MAX_TRADE_BONDLESS_TAKER: "50000"
  MIN_BOND_SIZE: "1"
  MIN_FLAT_ROUTING_FEE_LIMIT: "10"
  MIN_FLAT_ROUTING_FEE_LIMIT_REWARD: "2"
  MIN_PUBLIC_ORDER_DURATION: "0.166"
  MIN_SWAP_AMOUNT: "10000"
  MIN_SWAP_FEE: "0.01"
  MIN_SWAP_POINT: "0.35"
  MIN_TRADE: '20000 '
  NETWORK: 'testnet'
  NODE_ALIAS: "'\U0001F916RoboSatsâš¡(RoboDevs)'"
  NODE_ID: '033b58d7......'
  ONION_LOCATION: ''
  PAYOUT_TIMEOUT_SECONDS: "90"
  PENALTY_TIMEOUT: "60"
  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: '5432'
  PROPORTIONAL_ROUTING_FEE_LIMIT: "0.001"
  REDIS_URL: 'redis://redis:6379/1'
  RETRY_TIME: "1"
  REWARD_TIP: "100"
  REWARDS_TIMEOUT_SECONDS: "30"
  SLASHED_BOND_REWARD_SPLIT: "0.5"
  SWAP_FEE_SHAPE: 'exponential'
  SWAP_LAMBDA: "8.8"
  TELEGRAM_BOT_NAME: ''
  TOR_PROXY: 'tor:9050'
  USE_TOR: 'True'
  LND_VERSION: v0.15.0-beta